name: Publish on GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src/website

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ping: ${{ secrets.DESTINATION_HOST }}

      - name: DEBUG List Current folder
        run: ls -la

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Build site
        run: deno task build

      - name: Copy to Remote Server
        uses: pierrickdelrieu/scp-action@0.1.2
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          ssh_port: ${{ secrets.DESTINATION_SSH_PORT }}
          ssh_username: ${{ secrets.SSH_USERNAME }}
          ssh_key: ${{ secrets.SSH_KEY }}
          source_dir: 'src/website/_site/'
          destination_dir: ${{ secrets.DESTINATION_FOLDER }}
          rm: true

      - name: Fix well-known
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DESTINATION_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: mv ${{ secrets.DESTINATION_FOLDER }}/_well-known ${{ secrets.DESTINATION_FOLDER }}/.well-known
