name: Blob storage website CI

on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: remove .git
      run: rm -rf .git && ls -la
      
    - name: remove .github
      run: rm -rf .github && ls -la
      
    - name: remove .vscode
      run: rm -rf .vscode && ls -la
      
    - name: remove .gitignore
      run: rm -rf .gitignore && ls -la
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Clean website
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob delete-batch  -s '$web' --pattern '*' --account-name ${{ vars.STORAGEACCOUNTNAME }} --auth-mode key

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ vars.STORAGEACCOUNTNAME }} --overwrite true --auth-mode key -d '$web' -s .
            
    - name: Purge Azure CDN Profile endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "personal-cdnp-website" --name "${{ vars.STORAGEACCOUNTNAME }}" --resource-group "personal-rg-northeu"

    - name: Azure logout
      run: |
            az logout
      if: always()
